### ISSUE TITLE
FLASH DAQ info link broken

### ISSUE THREAD

**Issue by balerion** [momentoscope/HextofOfflineAnalyzer#20]
the link to the desy webpage giving info for the daq channels is broken in the last section of the readme. Does anyone have the correct link?

**Comment by RealPolitiX** [comment]
I think that page is not always available, DESY has maintenance schedule

**Comment by balerion** [comment]
Ah, ok. should I close the issue? or do we want a cached version linked?

**Comment by balerion** [comment]
there was a problem with the ~ character. Fuixed by using google url shortner: if anyone has a better idea, please implement =)
